version: '3'
services:
  web:
    image: nginx
    volumes:
    - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    - ./www/:/var/www/html
    ports:
    - 80:80
    depends_on:
    - php
    - db

  php:
    build: docker
    volumes:
    - ./docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    - ./www/:/var/www/html
  composer:
    image: composer
    volumes:
    - ./www/:/app
    command: install

  db:
    image: postgres:10.1
    environment:
    - POSTGRES_DB=${DB_NAME}
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
    - 5432:5432
    volumes:
    - ./docker/postgres/:/docker-entrypoint-initdb.d/